version: "3"

services:
  app:
    image: pottava/realize:1.2
    command: run
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/go/src/github.com/pottava/docker-webui/
      - ./:/go/src/github.com/pottava/docker-webui/.realize/
    working_dir: /go/src/github.com/pottava/docker-webui
    environment:
      - APP_MODE=development
      - APP_LOG_LEVEL=99
      - APP_VIEW_ONLY=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_CERT_PATH=
      - CONFIG_FILE_PATH=/go/src/github.com/pottava/docker-webui/development/config.json
    container_name: app

  gulp:
    image: docker-webui/assets
    build: ./assets
    command: gulp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/gulp/monitor/
    container_name: gulp
